language: node_js
node_js:
  - "8"
cache: npm

install:
  - apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install
