language: node_js
node_js:
  - "8"
cache: npm

before_install:
  - git submodule init
  - git submodule update
  - cd ./dpki-lite.js
  - git apply ../dpki-lite.patch
  - cd ../integration_tests
  - npm install
  - cd ..

jobs:  
  include:
    - stage: "Tests"
      - script: npm run test
      name: "Unit Tests"
      - script: cd integration_tests && npm run test
      name: "Integration Tests"
